# KNN Similarity atau Menghitung Jarak (manual)

**Nama  : Rizki Ardian Samudra**

**NIM   : 210411100179**

**Kelas : Penambangan Data-C**

**1.   Data Awal**

In [8]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
pd.options.mode.chained_assignment = None  #menghilangkan peringatan

file_url = 'https://drive.google.com/file/d/1zjQilkcbW9AlhC_NuRI-tkR2vPIYKV7G/view?usp=share_link'

file_id = file_url.split('/')[-2]
dwn_url = "https://drive.google.com/uc?id=" + file_id
df = pd.read_csv(dwn_url, sep=';')

jumlah_baris = df.shape[0]
df.head(jumlah_baris)

     outlook humidity  windy play temperature
0      sunny     high  False   no         hot
1      sunny     high   True   no         hot
2   overcast     high  False  yes         hot
3      rainy     high  False  yes        mild
4      rainy   normal  False  yes        cool
5      rainy   normal   True   no        cool
6      sunny     high  False   no        mild
7      sunny   normal  False  yes        cool
8      rainy   normal  False  yes        mild
9      sunny   normal   True  yes        mild
10  overcast     high   True  yes        mild
11  overcast   normal  False  yes         hot
12     rainy     high   True   no        mild
13  overcast   normal   True  yes         NaN

**2.   Menghitung jarak pada nominal/categorical**

In [9]:
category = df[['outlook']]
jumlah_kolom = category.shape[1]

for index, row in category.iterrows():
    if category.iloc[13]['outlook'] == category.iloc[index]['outlook']:
      category.loc[index,'jarak'] = (jumlah_kolom - 1) / jumlah_kolom
    else:
      category.loc[index,'jarak'] = (jumlah_kolom - 0) / jumlah_kolom

category.head(jumlah_baris)

     outlook  jarak
0      sunny    1.0
1      sunny    1.0
2   overcast    0.0
3      rainy    1.0
4      rainy    1.0
5      rainy    1.0
6      sunny    1.0
7      sunny    1.0
8      rainy    1.0
9      sunny    1.0
10  overcast    0.0
11  overcast    0.0
12     rainy    1.0
13  overcast    0.0

**3.   Menghitung jarak pada biner**

In [10]:
biner = df[['humidity', 'windy', 'play']]
jumlah_kolom = biner.shape[1]

for index, row in biner.iterrows():
  if biner.iloc[13]['humidity'] == biner.iloc[index]['humidity']:
      biner.loc[index,'bin_humidity'] = 1
  else:
      biner.loc[index,'bin_humidity'] = 0
  if biner.iloc[13]['windy'] == biner.iloc[index]['windy']:
      biner.loc[index,'bin_windy'] = 1
  else:
      biner.loc[index,'bin_windy'] = 0
  if biner.iloc[13]['play'] == biner.iloc[index]['play']:
      biner.loc[index,'bin_play'] = 1
  else:
      biner.loc[index,'bin_play'] = 0

biner.head(jumlah_baris)

   humidity  windy play  bin_humidity  bin_windy  bin_play
0      high  False   no           0.0        0.0       0.0
1      high   True   no           0.0        1.0       0.0
2      high  False  yes           0.0        0.0       1.0
3      high  False  yes           0.0        0.0       1.0
4    normal  False  yes           1.0        0.0       1.0
5    normal   True   no           1.0        1.0       0.0
6      high  False   no           0.0        0.0       0.0
7    normal  False  yes           1.0        0.0       1.0
8    normal  False  yes           1.0        0.0       1.0
9    normal   True  yes           1.0        1.0       1.0
10     high   True  yes           0.0        1.0       1.0
11   normal  False  yes           1.0        0.0       1.0
12     high   True   no           0.0        1.0       0.0
13   normal   True  yes           1.0        1.0       1.0

In [11]:
biner_new = biner[['bin_humidity', 'bin_windy', 'bin_play']]

biner_new['q'] = 0
biner_new['r'] = 0
biner_new['s'] = 0
biner_new['t'] = 0
biner_new['jarak'] = 0

for index, row in biner_new.iterrows():
  if biner_new.loc[13,'bin_humidity'] == 1 and biner_new.loc[index,'bin_humidity'] == 1:
    biner_new.loc[index, 'q'] += 1
  if biner_new.loc[13,'bin_humidity'] == 0 and biner_new.loc[index,'bin_humidity'] == 1:
    biner_new.loc[index, 'r'] += 1
  if biner_new.loc[13,'bin_humidity'] == 1 and biner_new.loc[index,'bin_humidity'] == 0:
    biner_new.loc[index, 's'] += 1
  if biner_new.loc[13,'bin_humidity'] == 0 and biner_new.loc[index,'bin_humidity'] == 0:
    biner_new.loc[index, 't'] += 1

  if biner_new.loc[13,'bin_windy'] == 1 and biner_new.loc[index,'bin_windy'] == 1:
    biner_new.loc[index, 'q'] += 1
  if biner_new.loc[13,'bin_windy'] == 0 and biner_new.loc[index,'bin_windy'] == 1:
    biner_new.loc[index, 'r'] += 1
  if biner_new.loc[13,'bin_windy'] == 1 and biner_new.loc[index,'bin_windy'] == 0:
    biner_new.loc[index, 's'] += 1
  if biner_new.loc[13,'bin_windy'] == 0 and biner_new.loc[index,'bin_windy'] == 0:
    biner_new.loc[index, 't'] += 1

  if biner_new.loc[13,'bin_play'] == 1 and biner_new.loc[index,'bin_play'] == 1:
    biner_new.loc[index, 'q'] += 1
  if biner_new.loc[13,'bin_play'] == 0 and biner_new.loc[index,'bin_play'] == 1:
    biner_new.loc[index, 'r'] += 1
  if biner_new.loc[13,'bin_play'] == 1 and biner_new.loc[index,'bin_play'] == 0:
    biner_new.loc[index, 's'] += 1
  if biner_new.loc[13,'bin_play'] == 0 and biner_new.loc[index,'bin_play'] == 0:
    biner_new.loc[index, 't'] += 1
  
  biner_new.loc[index, 'jarak'] = (biner_new.loc[index, 'r'] + biner_new.loc[index, 's']) / (biner_new.loc[index, 'q'] + biner_new.loc[index, 'r'] + biner_new.loc[index, 's'] + biner_new.loc[index, 't'])

biner_new.head(jumlah_baris)

    bin_humidity  bin_windy  bin_play  q  r  s  t     jarak
0            0.0        0.0       0.0  0  0  3  0  1.000000
1            0.0        1.0       0.0  1  0  2  0  0.666667
2            0.0        0.0       1.0  1  0  2  0  0.666667
3            0.0        0.0       1.0  1  0  2  0  0.666667
4            1.0        0.0       1.0  2  0  1  0  0.333333
5            1.0        1.0       0.0  2  0  1  0  0.333333
6            0.0        0.0       0.0  0  0  3  0  1.000000
7            1.0        0.0       1.0  2  0  1  0  0.333333
8            1.0        0.0       1.0  2  0  1  0  0.333333
9            1.0        1.0       1.0  3  0  0  0  0.000000
10           0.0        1.0       1.0  2  0  1  0  0.333333
11           1.0        0.0       1.0  2  0  1  0  0.333333
12           0.0        1.0       0.0  1  0  2  0  0.666667
13           1.0        1.0       1.0  3  0  0  0  0.000000

**4.   Menggabungkan jarak categorical dan jarak biner**

In [12]:
total_jarak = category[['jarak']] + biner_new[['jarak']]
total_jarak.head(jumlah_baris)

       jarak
0   2.000000
1   1.666667
2   0.666667
3   1.666667
4   1.333333
5   1.333333
6   2.000000
7   1.333333
8   1.333333
9   1.000000
10  0.333333
11  0.333333
12  1.666667
13  0.000000

**5.   Mengurutkan data berdasarkan jarak yang terkecil**

In [13]:
df_new = df.copy()
df_new['jarak'] = total_jarak[['jarak']]
df_new = df_new.drop(df_new.index[-1]) #menghapus index terakhir karena itu dirinya sendiri
df_new = df_new.sort_values('jarak') #sorting dari nilai terkecil

df_new.head(jumlah_baris)

     outlook humidity  windy play temperature     jarak
10  overcast     high   True  yes        mild  0.333333
11  overcast   normal  False  yes         hot  0.333333
2   overcast     high  False  yes         hot  0.666667
9      sunny   normal   True  yes        mild  1.000000
4      rainy   normal  False  yes        cool  1.333333
5      rainy   normal   True   no        cool  1.333333
7      sunny   normal  False  yes        cool  1.333333
8      rainy   normal  False  yes        mild  1.333333
1      sunny     high   True   no         hot  1.666667
3      rainy     high  False  yes        mild  1.666667
12     rainy     high   True   no        mild  1.666667
0      sunny     high  False   no         hot  2.000000
6      sunny     high  False   no        mild  2.000000

**6.   Berdasarkan data diatas dapat kita tarik kesimpulan nilai yang sering muncul dari tiga baris teratas pada kolom temperature adalah hot (modus) sehingga kita bisa isi baris index ke-13 yang kosong dengan 'hot'**

In [14]:
df_hasil = df.copy()
df_hasil.loc[13, 'temperature'] = 'hot'
df_hasil.head(jumlah_baris)

     outlook humidity  windy play temperature
0      sunny     high  False   no         hot
1      sunny     high   True   no         hot
2   overcast     high  False  yes         hot
3      rainy     high  False  yes        mild
4      rainy   normal  False  yes        cool
5      rainy   normal   True   no        cool
6      sunny     high  False   no        mild
7      sunny   normal  False  yes        cool
8      rainy   normal  False  yes        mild
9      sunny   normal   True  yes        mild
10  overcast     high   True  yes        mild
11  overcast   normal  False  yes         hot
12     rainy     high   True   no        mild
13  overcast   normal   True  yes         hot